db_password    = "SuperSecretPassword"
allocation_id  = "eipalloc-xxxxxxxxxxxxxxxxx"
main_domain_name  = "www.example.com"
github_token      = "github_pat_somelongtoken"
github_user       = "someusername"
github_repo       = "someusernamerepo"
letsencrypt_email = "admin@example.com"