---
- name: "ensure asdf_dir presence and ownership"
  file:
    path: "/home/deploy/.asdf"
    owner: deploy
    group: deploy
    state: directory

- name: Ensure dependencies are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential
      - curl
      - git
      - acl
  # become: yes
      
- name: Add asdf to the shell profile
  lineinfile:
    path: ~/.bashrc
    line: '. /home/deploy/.asdf/asdf.sh'
    create: true


- name: Clone the asdf repository
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: /home/deploy/.asdf/
    version: v0.10.2
  become: yes
  become_user: deploy
      
- name: Add asdf to the shell profile
  lineinfile:
    path: ~/.bashrc
    line: '. $HOME/.asdf/completions/asdf.bash'
    create: true

- name: Reload the shell profile
  shell: . ~/.bashrc

# - name: Install asdf plugins
#   shell: asdf plugin-add <PLUGIN_NAME>
#   with_items:
#     - nodejs
#     - python
#     - ruby
#     - golang

# - name: Install asdf versions
#   shell: asdf install <PLUGIN_NAME> <VERSION>
#   with_items:
#     - nodejs: 12.16.3
#     - python: 3.8.2
#     - ruby: 2.7.1
#     - golang: 1.14.2
